### ISSUE TITLE
'Find Unused Step Definitions' command doesn't handle 'StepDefinition' attributes well

### ISSUE THREAD

**Issue by UL-ChrisGlew** [reqnroll/Reqnroll.VisualStudio#22]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Content of reqnroll.json (if present)

{
  "bindingCulture": {
    "name": "en-GB"
  },
  "language": {
    "feature": "en-GB"
  }
}

### Issue Description

Step definitions declared with the 'StepDefinition' attribute are showing multiple times inside the new 'Find Unused Step Definitions' menu option. These appear to show Given/Then/When usages, and implies that the Step Definition is unused - which is not always the case.

Is it possible to change this behavior to show which methods decorated with 'StepDefinition' are unused?

### Steps to Reproduce

1. Have a Reqnroll project
2. Create a new 'Step Definition' file, adding the [Binding] attribute
3. Create a new step definition, using the 'StepDefinition' attribute. For example: [StepDefinition("I can do the thing")]
![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/32386512/cb1f2595-54b7-405f-82bf-a97386361194)
6. Use this StepDefinition in a feature file. For example: **Given I can do the thing**
![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/32386512/5764628e-1d04-468a-a824-b8cf948c9db7)
8. View the 'Find Unused Step Definitions' context on the Step Definition file.
9. You will see:
   * [Then("I can do the thing")] 
   * [When("I can do the thing")]
![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/32386512/c6c841bd-320f-482c-bc99-98181a252f3c)

**Comment by gasparnagy** [comment]
That makes sense. 

Reqnroll internally generates three step definition binding from the `[StepDefinition]` attribute and this is what the VS extension receives. At that point it is not possible to tell if they were coming from the same attribute or separate ones, but if they belong to the exact same method and have the exact same expression we could assume that these were created using `[StepDefinition]`.

The improvement could be done by modifying the `UnusedStepDefinitionsFinder.FindUnused` method (plus add tests for it to `FindUnusedStepDefinitionsCommandTests`).

I think the implementation should:
- add an additional loop before the return ([here](https://github.com/reqnroll/Reqnroll.VisualStudio/blob/main/Reqnroll.VisualStudio/Editor/Services/UnusedStepDefinitionsFinder.cs#L31))
- go through the ones that are considered unused (`stepDefUsageCounts.Where(x => x.Value == 0)`)
- for each of these, check if there is a used one (`stepDefUsageCounts.Where(x => x.Value > 0)`) that has the same `Expression` and the same `Implementation` (ref equals).
- If there is one, it should not be counted as unused

Do you want to try making a PR for this?

**Comment by UL-ChrisGlew** [comment]
@gasparnagy Sure I'm happy to contribute, just a couple of questions:

1. Is it possible to debug the Visual Studio extension? I can't seem to debug/run from the **Reqnroll.VisualStudio.Package** project without installing a 'preview' package into Visual Studio?
2. I don't seem to have rights to create a new branch in this repository, is that something that could be sorted?

Thanks!

**Comment by UL-ChrisGlew** [comment]
@gasparnagy Thanks for sorting that, I can push new branches/etc to the repository now.

From the guide it says:
 > You can also set the Reqnroll.VisualStudio.Package project as startup project. It is configured in a way that if you use the Start Debugging command (F5) it will automatically start the Visual Studio Experimental Instance with the debugger attached. So you can debug the full life-cycle of the extension, right from the loading. (Similarly, the "Start Without Debugging" (Ctrl+F5) is also working that simply starts Visual Studio Experimental Instance and you don't have to find it in the Start menu.)

For me, when loading the extension project, I don't see the option to debug, and get the following popup:

![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/32386512/9dcf9b97-4304-488e-a98e-192519215bbe)
![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/32386512/dceb0d87-2763-4371-858f-11cd024fd1a5)

Normally I'd think it was something with my Visual Studio install, but I'm able to debug/launch other extensions fine.

**Comment by gasparnagy** [comment]
That is strange. But I think you can just set the debug config to debug the devenv.exe process (from the vs install location) with the params `/rootSuffix Exp`. But I will check it once I am back at my desk.

**Comment by gasparnagy** [comment]
I have checked and indeed the package project cannot be started by default. I might have created a launch profile earlier. Anyway: I have documented the steps to configure the launch profile: https://github.com/reqnroll/Reqnroll.VisualStudio/blob/main/CONTRIBUTION.md#debug-the-visual-studio-package

I hope it will work for you as well.

**Comment by UL-ChrisGlew** [comment]
@gasparnagy That worked great, thanks for writing that - hopefully it helps other contributors in the future as well 😃

**Comment by UL-ChrisGlew** [comment]
@gasparnagy unrelated to this specific issue, I've noticed that the 'Find Unused Step Definitions' doesn't handle it very well if step definitions are included in a separate project.

I've tried to access the context menu option from this separate project and it throws the error below. Is this intended behavior or something that also needs to be fixed? I'm happy to look into this while I'm in this area.

![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/32386512/0c0e0809-4270-41f8-88ed-1a49c8a0519f)

**Comment by gasparnagy** [comment]
@UL-ChrisGlew Thx. We were going back and forth with @clrudolphi about how the projects should be handled. So you should definitely check the discussion we had from [here](https://github.com/reqnroll/Reqnroll.VisualStudio/pull/8#issuecomment-1987184875) down. We also created a scenario to cover the cases, but it can happen that we still miss a combination.

**Comment by clrudolphi** [comment]
IIRC we decided to not look at external assemblies because of the risks of false positives.
An external step definition assembly may be used by many different projects/solutions. A step that is not used by one project may be used by another. To mark it as 'unused' would be misleading. 
We could perhaps fine-tune that with some heuristics. If the external step definition project is incorporated via Nuget for example it would be excluded but if the project containing the steps is a project within the current solution then perhaps we include it.

**Comment by UL-ChrisGlew** [comment]
Ah okay, it's not as simple as a problem to solve as I first thought - it's not a dealbreaker at the moment for us but would be useful in the future.

**Comment by gasparnagy** [comment]
I close this issue now as we will probably not be able to improve this in the close future. If anything comes up, feel free to reopen.
