### ISSUE TITLE
Define Steps does produces incorrect regex for step definition attribute

### ISSUE THREAD

**Issue by TimMurphy** [reqnroll/Reqnroll.VisualStudio#28]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Content of reqnroll.json (if present)

```
{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",

  "bindingAssemblies": [
      {
          "assembly": "CroquetScores.TestHelpers"
      }
  ]
}

```

### Issue Description

When a step in a feature includes brackets (), the regex for the step definition created by Define Steps... is incorrect .

As an example if you have the following step

```
When I call the integer.ToString()
```

The generated step is:

```
[When("I call the integer.ToString\\)")]
public void WhenICallTheInteger_ToString()
{
    throw new PendingStepException();
}

```
Notice how the brackets of the steps are written as \\). The generated code should be:

```
[When(@"I call the integer.ToString\(\)")]
public void WhenICallTheInteger_ToString()
{
    throw new PendingStepException();
}
```

### Steps to Reproduce

Create a feature with the following scenario.

```
Scenario: Brackets example
	Given I have the integer '2'
	When I call the integer.ToString()
	Then the result should be a string '2'
```

Right click in the feature file and select **Define Steps...**.

The Define Steps window will show the when step as

```
[When("I call the integer.ToString\\)")]
public void WhenICallTheInteger_ToString()
{
     throw new PendingStepException();
 }
```

**Comment by clrudolphi** [comment]
@gasparnagy - I've attempted to find an authoritative source online for what characters are legal in a step, but not having any luck finding anything that addresses this question. Which non-alphanumeric characters are allowed (or not allowed)?
With that, I'll take a look at what needs to be changed to address this issue.

**Comment by TimMurphy** [comment]
Thanks

**Comment by clrudolphi** [comment]
@TimMurphy here are my findings so far. 
When using the default stepDefinitionSkeletonStyle of Cucumber expressions, I get the same behavior you note in this issue.
When I use the older Regex style, I get the following code skeleton generated by the "Define Steps..." Command: 
```c#
        [When(@"I call the integer\.ToString\(\) method")]
        public void WhenICallTheInteger_ToStringMethod()
        {
            throw new PendingStepException();
        }
``` 

Would the above work for you? Are you wanting to use Regex expressions or Cucumber expressions?
If the above is OK, then try using the Regex style snippet generator by modifying your reqnroll.json configuration file and insert the following: 
```javascript
"trace": { "stepDefinitionSkeletonStyle": "RegexAttribute" },
```   
See the [Documentation](https://docs.reqnroll.net/latest/installation/configuration.html#trace) for details on the reqnroll.json configuration file.

HTH.
I'll keep looking for an explanation of the behavior while using the Cucumber expression style.

**Comment by TimMurphy** [comment]
@clrudolphi 

That works perfect;y. Thanks for that and for all your work to create and main Reqnrol

**Comment by gasparnagy** [comment]
For the record, the cucumber expression syntax specification is here: https://github.com/cucumber/cucumber-expressions?tab=readme-ov-file#escaping

**Comment by gasparnagy** [comment]
@TimMurphy Thank you for your sponsorship! 🙏🤘
