### ISSUE TITLE
VSIX Package has Security Vulnerabilities

### ISSUE THREAD

**Issue by sjxckson** [reqnroll/Reqnroll.VisualStudio#32]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

Our IT Security team have flagged vulnerabilities with the VSIX Package where System.Net.Http is being used but our internal package scanner is blocking it therefore we cannot use this VSIX package

### Steps to Reproduce

Run Security Scan on VSIX Package

**Comment by gasparnagy** [comment]
We had to undo the fix because of VS compatibility issues (see #37), so essentially this issue is still open again.
