### ISSUE TITLE
"Go to Definition" or "Go to Step Definition" not available in feature file

### ISSUE THREAD

**Issue by polatsbf** [reqnroll/Reqnroll.VisualStudio#36]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

I just migrated from specflow to reqnroll. Tests running without any issue. Framework has been built successfully. But feature file is weird, it's like plain text. When I right click any step, I don't see "Go to Step Definition". Screenshot's been attached. Same thing in StepDef classes. When I right click to any step def, I don't see anything to go to implemented feature file line. 
![Screenshot 2024-09-17 121911](https://github.com/user-attachments/assets/bad3b881-bc24-420c-8e78-737f7148306d)
![Screenshot 2024-09-17 121951](https://github.com/user-attachments/assets/5547e87b-c11a-468d-87d9-6cdb18579db8)

### Steps to Reproduce

Nan

**Comment by polatsbf** [comment]
I just noticed that I forgot to enable Reqnroll extension. all good now. Could you just delete the ticket please. Sorry!

**Comment by gasparnagy** [comment]
@polatsbf no worries. thx for sending an update. closing the ticket.
