### ISSUE TITLE
Reqnroll Extension v2024.3.152 does not work on Visual Studio 17.11.4

### ISSUE THREAD

**Issue by UL-ChrisGlew** [reqnroll/Reqnroll.VisualStudio#37]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

When attempting to load a Reqnroll project on the latest version of Visual Studio 2022 with the latest Reqnroll extension installed, the extension will not load and functionality is not present. 

### Steps to Reproduce

1. Have a Reqnroll solution
2. Install latest Visual Studio 2022 updates
3. Install latest Reqnroll extension (v2024.3.152)
4. Extension functionality is not present.

![image](https://github.com/user-attachments/assets/974bd2ec-b2c6-4442-afc1-e70adcb2a52a)

### Workaround

**We have issued a hotfix, to the simplest workaround is to update the package to v2024.4.154 that should work.**

An alternative workaround for this issue would be to downgrade the Visual Studio 2022 extension to the previous version.

The download for the previous version can be found here:

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Reqnroll/vsextensions/ReqnrollForVisualStudio2022/2024.2.93/vspackage

To downgrade, you'll need to

- Uninstall the current Reqnroll for Visual Studio 2022 extension
- Disable automatic updates (for now):
![image](https://github.com/user-attachments/assets/090df45b-3009-45b6-a148-45c581300e48)
- Then close Visual Studio 2022 and install the VSIX file downloaded in the URL above.

**Comment by UL-ChrisGlew** [comment]
I can confirm that when downgrading to the previous release (2024.2.93), the extension works as expected on the same Visual Studio 2022 version:

![image](https://github.com/user-attachments/assets/2a0dc465-aa45-455f-bfb1-e57e7d59afe7)

**Comment by UL-ChrisGlew** [comment]
anhtuan266 posted about this in the relevant discussion, which could suggest some kind of dependency issue?

![image](https://github.com/user-attachments/assets/00bd9c85-57e5-4b75-a808-3c7c66208ee0)

**Comment by UL-ChrisGlew** [comment]
Debugging the Visual Studio Extension locally, it seems to work fine on commit [#e22](https://github.com/reqnroll/Reqnroll.VisualStudio/commit/e221b186acd80528033033a7a21251e6f5691c22). Might be something to do with updating dependencies @gasparnagy on [#41a](https://github.com/reqnroll/Reqnroll.VisualStudio/commit/41a363e8d8d651c022b8c7f3a4c7a1079b2883d8)?

**Comment by alahane-techtel** [comment]
thanks guys for being so quick on this. Meanwhile, is there a way I can get 2024.2.93 version?

**Comment by alahane-techtel** [comment]
amazing. I just tried it. All works absolutely fine now :) Thanks again @UL-ChrisGlew 
You guys are doing a fantastic job. Cant tell you how much relieved I'm by seeing this support. I was scared today, when after a couple of years since using Specflow last time, today when I saw it dead, I was like freaked out. Now I'm confident :)

**Comment by UL-ChrisGlew** [comment]
@gasparnagy I'm seeing the below in the activity log when loading a project, could be related:

![image](https://github.com/user-attachments/assets/3f52fa04-6ddf-479e-9015-5e1c412f59d5)

**Comment by gasparnagy** [comment]
The issue is not reproducible on my machine (I have just upgraded to Visual Studio 17.11.4), so I decided to apply a hotfix and reverted the commit that is most probably causing the problem. My plan is to release this ASAP and diagnose & fix the original issue without the stress of users being blocked.

I need help:

1. There is a [release candidate in the pipeline](https://github.com/reqnroll/Reqnroll.VisualStudio/actions/runs/10921469212). For a few of those who experienced the issue, please [download the generated VSIX](https://github.com/reqnroll/Reqnroll.VisualStudio/actions/runs/10921469212/artifacts/1947512824) try to install it (close VS and double click on the vsix file and follow the instructions) and inform if the extension loads correctly.
2. If I get positive responses, I will release the hotfix.
3. After that, again for those who can reproduce it, please try to analyze the issue. The mentioned assembly has been upgraded in the reverted commit, so it is surely related, but the details are unknown. It is generally very hard to diagnose such issues, but I have written earlier [some notes about it in the CONTRIBUTION.md guide](https://github.com/reqnroll/Reqnroll.VisualStudio/blob/main/CONTRIBUTION.md#diagnosing-mef-composition-errors), please check it and hopefully you get closer to it.

**Comment by UL-ChrisGlew** [comment]
@gasparnagy  - Tested that VSIX file, seems to fix the issue.

One thing I did notice with the previous version is that the version of System.IO.Abstractions we're now using has dependencies on other NuGet packages (TestableIO.System.IO.Abstractions and TestableIO.System.IO.Abstractions.Wrappers), which had assemblies missing from the output directory - possible there's more than just these missing?

**Comment by gasparnagy** [comment]
@UL-ChrisGlew thx for the quick reaction. The hotfix (v2024.4.154) is currently being published, it will be available in the marketplace within a few minutes.

It can be that the package is just simply missing some additional assemblies, and maybe I have some other extension that deployed that and that is why it is not reproducible here.

**Comment by JimCooperFromGmailAccount** [comment]
@gasparnagy  Works for me too

**Comment by UL-ChrisGlew** [comment]
> @UL-ChrisGlew thx for the quick reaction. The hotfix (v2024.4.154) is currently being published, it will be available in the marketplace within a few minutes.
> 
> It can be that the package is just simply missing some additional assemblies, and maybe I have some other extension that deployed that and that is why it is not reproducible here.

Possibly yes, I did have to test this on another machine with just that Reqnroll extension installed in order to see what's going on with this. Unfortunately the code is a bit of out my wheelhouse so I'm not 100% confident in figuring out what's going on - I'll try and have another look though.

**Comment by jdb0123** [comment]
v2024.3.152 also had the same described issue on our side. Can confirm that the hotfix (v2024.4.154) is working as expected.

**Comment by orifn1** [comment]
hotfix (v2024.4.154) works for me

**Comment by UL-ChrisGlew** [comment]
I've managed to 'fix' and replicate a before/after with the PR #39.

Testing done:

1. Replicated the setup seen by some users in Visual Studio 2022 17.11.4 and Reqnroll.VisualStudio v2024.3.152
2. Updated the relevant files to add the missing .dll files.
3. Tested using an experimental environment that correct behaviour is restored.
4. Closed everything and installed the debug package into Visual Studio 2022.
5. Validated that correct behaviour is still observed.

It's obviously a bit risky as it's very tricky to get error output/etc from these sort of changes - but given the error I was seeing in the ActvityLog.xml has dissappeared - it's doing something right at least!

**Comment by UL-ChrisGlew** [comment]
@gasparnagy I've had a play around and the extension does seem to work correctly with all updates re-applied and the missing files added back. Have re-raised #39 for review.

**Comment by orifn1** [comment]
> There is a CI build now that contains the proper fix by @UL-ChrisGlew, and I would like to release this soon to address the security issues. To avoid the situation we had last time, @orifn1, @jdb0123, @JimCooperFromGmailAccount could you please help trying it out with the VSIX of this CI build downloadable from [here](https://github.com/reqnroll/Reqnroll.VisualStudio/actions/runs/10935324492/artifacts/1951483763).
> 
> If it works, you can even keep it installed. It is basically the released version plus the problematic package updates.

it works for me
![image](https://github.com/user-attachments/assets/707e7117-84d9-4218-9e7d-d2d46f33ae83)

**Comment by gasparnagy** [comment]
@UL-ChrisGlew Funny. Try to uninstall completely. Start VS. Wait until uninstall finished. Start VS again (so it updates caches). Close it again and after that try installing it from VSIX again.

**Comment by JimCooperFromGmailAccount** [comment]
I had that with the 152 update. VS gets a wee bit confused from time to time :-)

Uninstall it (it took 2 tries for me) and reinstall and it gets VS back to normal

**Comment by JimCooperFromGmailAccount** [comment]
Looks good for me too

**Comment by UL-ChrisGlew** [comment]
Yeah, I've tried uninstalling the extension completely, then installing from the Extensions manager - and updating the VSIX from the file provided and no dice - just won't show up in Visual Studio :/

**Comment by UL-ChrisGlew** [comment]
Okay, redownloaded the file and tried again and it worked okay - must have been a duff download 🤷

**Comment by gasparnagy** [comment]
Thx. Just for the record, sometimes in stange installation problems you can also try `devenv /ResetSkipPkgs` from a VS console. That basically attempts to reload packages that were skipped earlier due to errors. (Or something like that.)
