### ISSUE TITLE
Reqnroll extension v2024.5.169 fails in Visual Studio 17.8.3

### ISSUE THREAD

**Issue by ak-nex** [reqnroll/Reqnroll.VisualStudio#42]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

No

### Issue Description

After the latest update of the Reqnroll extension Visual Studio started to show the following error:
![image](https://github.com/user-attachments/assets/ef936c6b-0c3d-44ea-8e1c-5d37cb9871d4)

Visual Studio version: 17.8.3
Reqnroll extension version: v2024.5.169

Error part of ActivityLog.xml:
```
SetSite failed for package [ReqnrollVsPackage]Source: 'Reqnroll.VisualStudio.Package' Description: Не удалось загрузить файл или сборку "Microsoft.VisualStudio.Threading, Version=17.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.
System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "Microsoft.VisualStudio.Threading, Version=17.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.
File name: 'Microsoft.VisualStudio.Threading, Version=17.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Reqnroll.VisualStudio.Package.ReqnrollVsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
```

It seems that Visual Studio of version lower than 17.10 is out of support after the update.

### Steps to Reproduce

1) Install Visual Studio 17.8.3
2) Install Reqnroll extension v2024.5.169
3) Rerun Visual Studio

**Comment by ak-nex** [comment]
Oh, I found a similar error in [this comment](https://github.com/reqnroll/Reqnroll.VisualStudio/issues/37#issuecomment-2357848999). As a workaround I'll try to turn off autoupdate and downgrade the extension as @UL-ChrisGlew suggested (many thx :))

**Comment by bigsteiny** [comment]
I am also receiving this error now, on Version 17.4.18. I note that you have Russian (?) in your FileNotFound exceptions. I don't use that language set so (at least) it is not related to that. I am new to ReqNRoll, i had it running earlier based on my installation from around a week ago, and I think it was the update to the VS extension today that now caused this issue.

**Comment by gasparnagy** [comment]
@bigsteiny does it throw an error for the same assembly (`Microsoft.VisualStudio.Threading, Version=17.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`) as well?

@ak-nex @bigsteiny Could you please try if updating Visual Studio fixes the issue?

**Comment by gasparnagy** [comment]
@ak-nex @bigsteiny Please don't update your VS yet! I think I have found a fix and I would like you to confirm if it works.

**Comment by ak-nex** [comment]
@gasparnagy I took a vsix from [this build](https://github.com/reqnroll/Reqnroll.VisualStudio/actions/runs/11748278382) and confirm that everything works on Visual Studio 17.8.3 now. Thank you a lot, you're doing a great job!

**Comment by gasparnagy** [comment]
@ak-nex Super. Thx for the feedback. I will release it now.

**Comment by gasparnagy** [comment]
v2024.6.176 is out

**Comment by bigsteiny** [comment]
Confirmed this is working for me now also. Thanks @gasparnagy !
