### ISSUE TITLE
Feature file icons in the Solution Explorer are generic

### ISSUE THREAD

**Issue by EngSimoes** [reqnroll/Reqnroll.VisualStudio#5]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

The icon used is generic. 

![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/5269989/d4582ba2-7cbb-4cc4-b99e-a1a552ae3250)

### Steps to Reproduce

Navigate to a feature file in the Solution Explorer. 

Reqnroll extension version: 2024.1.49

**Comment by gasparnagy** [comment]
@EngSimoes Could you please check if the following registry entries are set for you?

`Computer\HKEY_CURRENT_USER\SOFTWARE\Classes\.feature`

![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/144701/44766468-96d0-4be2-ba14-bf0530a5b96c)

`Computer\HKEY_CURRENT_USER\SOFTWARE\Classes\Reqnroll.GherkinFile\DefaultIcon`

![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/144701/d457a3ed-7c5d-48f5-a056-21cdbd619e40)

And that the file `C:\Users\<yourusername>\AppData\Local\Reqnroll\gherkin_reqnrollvs.ico`  exists?

**Comment by EngSimoes** [comment]
Hi @gasparnagy, I have searched in the registry and there is no '.feature' folder, neither a Reqnroll.GherkinFile registry.

![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/5269989/96755df3-9617-4589-be7f-482a349b7790)

![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/5269989/08dd5c43-575a-465e-8b1a-d25d28e04107)


In the folder `\AppData\Local\Reqnroll\` there is only a .log file. 

![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/5269989/be05ee86-42cd-4ea7-baf7-3de64ec23a3c)


I've installed the Reqnroll extension through Visual Studio "Manage Extensions" dialog. 

Below details from Visual Studio.

------ 

Microsoft Visual Studio Community 2022
Version 17.9.0
VisualStudio.17.Release/17.9.0+34607.119
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

ASP.NET and Web Tools   17.9.195.45391
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.9.195.45391
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.9.195.45391
Azure Functions and Web Jobs Tools

C# Tools   4.9.0-3.24081.11+989117396f26e5453ff157df610d22ce45b6b0a9
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   12.0
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.9.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.9.2.2408002+5aec2f1744a2273d3e7157cc4cc1986f87f524d4
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.9.51.1
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.30103.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-3.24081.11+989117396f26e5453ff157df610d22ce45b6b0a9
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio Extension for Reqnroll   1.0
Visual Studio extension for working with Reqnroll projects and Gherkin feature files.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by EngSimoes** [comment]
Hi @gasparnagy, looks like I need to create a new Reqnroll project for the icon to exist. 
If I don't create a new Reqnroll project, the icon file will not exist. 

![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/5269989/9f7404fa-9753-471a-8b96-0e11dde42d33)

Basic new project created.

![image](https://github.com/reqnroll/Reqnroll.VisualStudio/assets/5269989/db5f77d2-b7a5-42e0-bcc8-8ba47469d441)

**Comment by gasparnagy** [comment]
@EngSimoes Oh. That is strange.

The icons are configured by `WelcomeService.CheckFileAssociation` that is invoked during first time installation and upgrade. 

The detection of first time installation and upgrade is done in an on-demand fashion, so only done when you actually do something (e.g. add a new project). 

The only thing I don't understand is why it was not triggered when you opened a feature file (because that should also trigger this). **Is it possible that at the time where there was no icons, no feature files were opened yet?**

Unfortunately it is not that easy to test it, because even if you uninstall the extension, it remembers that it was installed (to be able to recognize upgrades). If you want to play with this, you need to:
1. Close VS
2. Delete the Reg nodes mentioned above (maybe restart Windows to forget the icon association)
3. Delete the Reg node: `Computer\HKEY_CURRENT_USER\SOFTWARE\Reqnroll`

**Comment by gasparnagy** [comment]
Closing it because of inactivity. Please reopen if you have new details.
