### ISSUE TITLE
Create step definition snippets generates Reqnroll using statements for SpecFlow projects

### ISSUE THREAD

**Issue by gasparnagy** [reqnroll/Reqnroll.VisualStudio#6]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

Create step definition snippets generates Reqnroll using statements for SpecFlow projects

### Steps to Reproduce

- Open a SpecFlow project
- Add a new undefined step to a feature file
- Invoke "Define Steps..." and click "Create"
- The generated class does not compile

**Comment by clrudolphi** [comment]
@gasparnagy Now that #13 has been merged, can this be closed?
